apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  labels:
    app: web-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-con
        image: krishnamoorthy1/webapp:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
