# Create grafana deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000  
        
---
# Create grafana service 
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
  - port: 3000      # service listen
    targetPort: 3000  # endpoint listen
    protocol: TCP
    nodePort: 30000  # Node Port
  selector:
    app: grafana        
  type: NodePort  
